src/main/resources/templetes/header.html
=> 충동 테스트용 헤더

src/main/java/edu/kh/fit/main/controller/Maincontroller.java, src/main/java/edu/kh/fit/main/mapper/MainMapper.java, src/main/java/edu/kh/fit/main/service/MainService.java, src/main/java/edu/kh/fit/main/service/MainServiceImpl.java, src/main/java/edu/kh/fit/member/controller/MemberController.java, src/main/resources/mappers/main-mapper.xml, src/main/resources/templetes/header.html
=> Main 관련 java 파일

src/main/java/edu/kh/fit/main/controller/Maincontroller.java, src/main/java/edu/kh/fit/member/controller/MemberController.java, src/main/java/edu/kh/fit/member/mapper/MemberMapper.java, src/main/java/edu/kh/fit/member/service/MemberService.java, src/main/java/edu/kh/fit/member/service/MemberServiceImpl.java, src/main/java/edu/kh/fit/trainner/controller/TrainnerController.java, src/main/java/edu/kh/fit/trainner/mapper/TrainnerMapper.java, src/main/java/edu/kh/fit/trainner/service/TrainnerService.java, src/main/java/edu/kh/fit/trainner/service/TrainnerServiceImpl.java, src/main/resources/application.properties, src/main/resources/mappers/member-mapper.xml, src/main/resources/mappers/trainner-mapper.xml, src/main/resources/templates/common/signUp.html, src/main/resources/templates/login/login.html, src/main/resources/templates/member/memberMyPage.html, src/main/resources/templates/trainer/trainerMyPage.html
1. push 중 오류내용 수정.
2. 오타 수정
3. common/signUp.html 생성(여기에 회원/강사 가입 넣어주세요)
java코드 작성
1. 로그인
2. 로그 아웃
3. 회원가입
=> vsCode(작업 2개, login.html / signUp.html)

src/main/resources/static/css/common/footer.css, src/main/resources/static/css/common/header.css, src/main/resources/static/css/styles.css, src/main/resources/static/js/main.js, src/main/resources/templates/common/common.html, src/main/resources/templates/common/footer.html, src/main/resources/templates/common/header.html, src/main/resources/templates/common/main.html, src/main/resources/templates/index.html
20241011 
웰컴페이지, 메인페이지, 헤더, 푸터 작성
=> 20241011 웰컴페이지, 메인페이지, 헤더, 푸터 작성

src/main/resources/static/css/common/header.css, src/main/resources/static/css/login/login.css, src/main/resources/static/js/login/login.js, src/main/resources/static/js/main.js, src/main/resources/templates/login/login.html
=> 20241011 로그인페이지

src/main/java/edu/kh/fit/payments/controller/PaymentsController.java, src/main/java/edu/kh/fit/payments/mapper/PaymentsMapper.java, src/main/java/edu/kh/fit/payments/service/PaymentsService.java, src/main/java/edu/kh/fit/payments/service/PaymentsServiceImpl.java, src/main/resources/mappers/payments-mapper.xml
=> 20241018 결제수단 폴더 구조 설정만 완료

src/main/resources/templates/myPage/memberSideBar.html, src/main/resources/templates/myPage/trainerSideBar.html
=> 트레이너, 맴버 사이드바 수정

src/main/java/edu/kh/fit/trainer/controller/TrainerController.java, src/main/java/edu/kh/fit/trainer/dto/Trainer.java, src/main/java/edu/kh/fit/trainer/mapper/TrainerMapper.java, src/main/java/edu/kh/fit/trainer/service/TrainerService.java, src/main/java/edu/kh/fit/trainer/service/TrainerServiceImpl.java, src/main/resources/mappers/trainer-mapper.xml, src/main/resources/templates/common/main.html
=> 트레이너 패키지 오류 수정

src/main/resources/static/css/common/header.css, src/main/resources/static/js/main.js, src/main/resources/templates/common/header.html, src/main/resources/templates/common/main.html, src/main/resources/templates/common/memberHeader.html, src/main/resources/templates/common/trainerHeader.html, src/main/resources/templates/index.html
20241022 
웰컴페이지 헤더 푸터 충돌 방지 클래스명 변경, 
매핑 주소 변경, 
teacher -> trainer로 변경
=> 20241022 웰컴페이지 헤더 푸터 충돌 방지 클래스명 변경, 매핑 주소 변경, teacher -> trainer로 변경

src/main/java/edu/kh/fit/homeGym/controller/HomeGymController.java, src/main/java/edu/kh/fit/homeTraining/controller/HomeTrainingController.java, src/main/resources/templates/common/main.html
메인페이지에서 더보기 칸 누르면 홈짐, 홈트레이닝, 강사프로필 페이지로 이동하는것 구현
=> 메인페이지에서 더보기 칸 누르면 페이지로 이동하는것 구현

src/main/java/edu/kh/fit/board/controller/BoardController.java, src/main/java/edu/kh/fit/board/dto/Pagination.java, src/main/java/edu/kh/fit/trainer/dto/Trainer.java, src/main/resources/static/css/admin/contents.css, src/main/resources/static/js/mainPage.js, src/main/resources/templates/common/main.html, src/main/resources/templates/index.html
localhost/board/숫자 해결, 페이지네이션 dto 추가, mainPage.js 파일 생성
=> localhost/board/숫자 해결, 페이지네이션 dto 추가, mainPage.js 파일 생성

src/main/java/edu/kh/fit/admin/controller/AdminController.java, src/main/java/edu/kh/fit/admin/dto/Admin.java, src/main/java/edu/kh/fit/admin/mapper/AdminMapper.java, src/main/java/edu/kh/fit/admin/service/AdminService.java, src/main/java/edu/kh/fit/admin/service/AdminServiceImpl.java, src/main/java/edu/kh/fit/main/controller/Maincontroller.java, src/main/java/edu/kh/fit/member/controller/MemberController.java, src/main/resources/mappers/admin-mapper.xml, src/main/resources/mappers/board-mapper.xml, src/main/resources/static/js/admin/adminLogin.js, src/main/resources/templates/admin/adminLogin.html, src/main/resources/templates/admin/adminMyPage.html
=> admin 페이지 로그인 마이페이지 작성중

src/main/java/edu/kh/fit/payment/controller/PaymentController.java, src/main/resources/static/css/payment/payment.css, src/main/resources/templates/payment/payment.html
241023 payment 중간과정 커밋 / 구조 재변경
=> 241023 payment 중간과정 커밋 / 구조 재변경

src/main/java/edu/kh/fit/admin/controller/AdminController.java, src/main/resources/templates/admin/admin.html, src/main/resources/templates/admin/adminLogin.html, src/main/resources/templates/admin/adminMyPage.html
=> admin 로그인 페이지 연결

src/main/java/edu/kh/fit/payment/controller/OrderController.java, src/main/java/edu/kh/fit/payment/dto/Order.java, src/main/java/edu/kh/fit/payment/mapper/OrderMapper.java, src/main/java/edu/kh/fit/payment/service/OrderService.java, src/main/java/edu/kh/fit/payment/service/OrderServiceImpl.java, src/main/resources/mappers/order-mapper.xml, src/main/resources/templates/payment/kakaopayPopup.html, src/main/resources/templates/payment/orderResult.html
결제 후 내역 전송 기능구현 완료. 결제내역 html은 현재 설계중
=> 결제 후 내역 전송 기능구현 완료. 결제내역 html은 현재 설계중

src/main/java/edu/kh/fit/payment/controller/OrderController.java, src/main/java/edu/kh/fit/payment/mapper/OrderMapper.java, src/main/java/edu/kh/fit/payment/service/OrderService.java, src/main/java/edu/kh/fit/payment/service/OrderServiceImpl.java, src/main/resources/mappers/order-mapper.xml, src/main/resources/templates/payment/order-payment.html, src/main/resources/templates/payment/orderResult.html, src/main/resources/templates/payment/payment.html
241025 결제시스템 구축 완료 및 결제 내역 데이터 조회
=> 241025 결제시스템 구축 완료 및 결제 내역 데이터 조회

src/main/java/edu/kh/fit/admin/controller/AdminController.java, src/main/java/edu/kh/fit/admin/dto/Query.java, src/main/java/edu/kh/fit/admin/mapper/AdminMapper.java, src/main/java/edu/kh/fit/admin/service/AdminService.java, src/main/java/edu/kh/fit/admin/service/AdminServiceImpl.java, src/main/java/edu/kh/fit/main/dto/Report.java, src/main/java/edu/kh/fit/trainer/dto/Trainer.java, src/main/resources/mappers/admin-mapper.xml, src/main/resources/static/js/admin/active.js, src/main/resources/static/js/admin/trainer.js, src/main/resources/templates/admin/memberActive.html, src/main/resources/templates/admin/trainer.html, src/main/resources/templates/common/common.html
=> admin 회원관리 페이지 완성

src/main/java/edu/kh/fit/list/controller/MemberClassListController.java, src/main/java/edu/kh/fit/list/controller/TrainerClassListController.java, src/main/java/edu/kh/fit/list/mapper/MemberClassListController.java, src/main/java/edu/kh/fit/list/mapper/TrainerClassListMapper.java, src/main/java/edu/kh/fit/list/service/MemberClassListService.java, src/main/java/edu/kh/fit/list/service/MemberClassListServiceImpl.java, src/main/java/edu/kh/fit/list/service/TrainerClassListService.java, src/main/java/edu/kh/fit/list/service/TrainerClassListServiceImpl.java, src/main/java/edu/kh/fit/payment/dto/Refund.java, src/main/resources/templates/payment/orderResult.html
=> dto Update

src/main/java/edu/kh/fit/payment/controller/PaymentController.java, src/main/java/edu/kh/fit/payment/dto/Order.java, src/main/resources/mappers/order-mapper.xml, src/main/resources/mappers/payment-mapper.xml, src/main/resources/templates/payment/kakaopayPopup.html, src/main/resources/templates/payment/orderResult.html
241025 결제 DB 수정으로 인한 소스 update
=> 241025 결제 DB 수정으로 인한 소스 update

src/main/java/edu/kh/fit/board/dto/Board.java, src/main/java/edu/kh/fit/board/mapper/BoardMapper.java, src/main/java/edu/kh/fit/board/search/controller/SearchController.java, src/main/java/edu/kh/fit/board/search/dto/SearchResult.java, src/main/java/edu/kh/fit/board/search/mapper/SearchMapper.java, src/main/java/edu/kh/fit/board/search/service/SearchService.java, src/main/java/edu/kh/fit/board/search/service/SearchServiceImpl.java, src/main/resources/mappers/searchReulst-mapper.xml, src/main/resources/static/css/search/search.css, src/main/resources/static/js/search/search.js, src/main/resources/templates/common/main.html, src/main/resources/templates/like/like.html, src/main/resources/templates/search/results.html
241028 검색기능 구현 시작 / main.html slider.js 파일 미확인으로 삭제
=> 241028 검색기능 구현 시작 / main.html slider.js 파일 미확인으로 삭제

src/main/java/edu/kh/fit/board/dto/Comment.java, src/main/java/edu/kh/fit/member/controller/MemberController.java, src/main/java/edu/kh/fit/member/mapper/MemberMapper.java, src/main/java/edu/kh/fit/member/service/MemberService.java, src/main/java/edu/kh/fit/member/service/MemberServiceImpl.java, src/main/java/edu/kh/fit/trainer/service/TrainerServiceImpl.java, src/main/resources/mappers/member-mapper.xml, src/main/resources/templates/myPage/memberMyActivities.html
=> member관련 수정

src/main/java/edu/kh/fit/member/controller/MemberController.java, src/main/java/edu/kh/fit/trainer/controller/TrainerController.java, src/main/java/edu/kh/fit/trainer/dto/Trainer.java, src/main/java/edu/kh/fit/trainer/mapper/TrainerMapper.java, src/main/java/edu/kh/fit/trainer/service/TrainerService.java, src/main/java/edu/kh/fit/trainer/service/TrainerServiceImpl.java, src/main/resources/mappers/trainer-mapper.xml, src/main/resources/static/js/trainer/trainer.js, src/main/resources/templates/trainer/trainerDetail.html
=> trainerDetailPage

src/main/resources/templates/admin/trainerActive.html
=> admin trainerActive 파일 생성

src/main/java/edu/kh/fit/admin/controller/AdminController.java, src/main/java/edu/kh/fit/admin/mapper/AdminMapper.java, src/main/java/edu/kh/fit/admin/service/AdminService.java, src/main/java/edu/kh/fit/admin/service/AdminServiceImpl.java, src/main/java/edu/kh/fit/member/controller/MemberController.java, src/main/resources/mappers/admin-mapper.xml, src/main/resources/static/js/admin/member.js, src/main/resources/static/js/admin/memberActive.js, src/main/resources/templates/admin/member.html, src/main/resources/templates/admin/memberActive.html
admin Page CSS 제외 작성 완료
회원 관리 페이지
강사 관리 페이지 완성
=> admin Page CSS 제외 작성 완료

src/main/java/edu/kh/fit/trainer/controller/TrainerController.java, src/main/java/edu/kh/fit/trainer/mapper/TrainerMapper.java, src/main/java/edu/kh/fit/trainer/service/TrainerService.java, src/main/java/edu/kh/fit/trainer/service/TrainerServiceImpl.java, src/main/resources/mappers/trainer-mapper.xml, src/main/resources/static/css/board/classList.css, src/main/resources/static/js/classList/trainerClassList.js, src/main/resources/templates/classList/classList.html, src/main/resources/templates/classList/trainerClassList.html, src/main/resources/templates/trainer/trainer.html
=> 강사 마이페이지 내 강의 목록 조회 css제외 완료

src/main/resources/mappers/trainer-mapper.xml, src/main/resources/static/js/classList/trainerClassList.js, src/main/resources/templates/classList/classList.html
=> 강사 강의 목록 조회 img 추가

src/main/java/edu/kh/fit/board/controller/BoardController.java, src/main/java/edu/kh/fit/board/dto/Board.java, src/main/java/edu/kh/fit/board/mapper/BoardMapper.java, src/main/java/edu/kh/fit/board/service/BoardService.java, src/main/java/edu/kh/fit/board/service/BoardServiceImpl.java, src/main/java/edu/kh/fit/common/config/FileConfig.java, src/main/java/edu/kh/fit/trainer/service/TrainerService.java, src/main/resources/mappers/board-mapper.xml, src/main/resources/mappers/trainer-mapper.xml, src/main/resources/static/css/board/boardWrite.css, src/main/resources/static/css/board/classList.css, src/main/resources/static/js/board/boardWrite.js, src/main/resources/static/js/classList/trainerClassList.js, src/main/resources/templates/board/boardWrite.html, src/main/resources/templates/classList/classList.html
강사 게시글 작성 작성완료
trainerController - editBoard
게시글 작성은 mypage 내 강의 목록에서 가능
=> 강사 게시글 작성 작성완료

src/main/java/edu/kh/fit/payment/controller/OrderController.java, src/main/java/edu/kh/fit/payment/controller/PaymentController.java, src/main/java/edu/kh/fit/payment/dto/Order.java, src/main/resources/mappers/order-mapper.xml, src/main/resources/mappers/payment-mapper.xml, src/main/resources/templates/customer/faq.html, src/main/resources/templates/payment/kakaopayPopup.html, src/main/resources/templates/payment/orderResult.html
This reverts commit 1a48252658696117329ee15a0b17791db515e4bb.
=> Reapply "payment 경로 오류가 있어 연결하는 값 수정."

src/main/java/edu/kh/fit/main/controller/Maincontroller.java, src/main/java/edu/kh/fit/member/controller/MemberController.java, src/main/java/edu/kh/fit/member/service/MemberServiceImpl.java, src/main/java/edu/kh/fit/trainer/controller/TrainerController.java, src/main/java/edu/kh/fit/trainer/mapper/TrainerMapper.java, src/main/java/edu/kh/fit/trainer/service/TrainerService.java, src/main/java/edu/kh/fit/trainer/service/TrainerServiceImpl.java, src/main/resources/mappers/member-mapper.xml, src/main/resources/mappers/trainer-mapper.xml, src/main/resources/static/js/signUp/trainerSignUp.js, src/main/resources/templates/trainer/signUP.html
signUp 설정완료
강사회원가입 페이지 새로 생성
encoder 해제
=> signUp 설정완료

src/main/resources/templates/search/results.html
=> 241031 검색어 존재하지 않을 때 존재하지 않다고 말하는거 커밋

src/main/java/edu/kh/fit/admin/service/AdminServiceImpl.java, src/main/java/edu/kh/fit/trainer/controller/TrainerController.java, src/main/java/edu/kh/fit/trainer/mapper/TrainerMapper.java, src/main/java/edu/kh/fit/trainer/service/TrainerService.java, src/main/java/edu/kh/fit/trainer/service/TrainerServiceImpl.java, src/main/resources/mappers/admin-mapper.xml, src/main/resources/mappers/trainer-mapper.xml, src/main/resources/static/js/admin/trainer.js, src/main/resources/static/js/trainer/trainerDashBoard.js, src/main/resources/templates/trainer/trainerDashBoard.html
관리자 대시보드. 관리자 로그인 수정
, 관리자 강사관리 회원상태변경 버튼 활성화
=> 관리자 대시보드. 관리자 로그인 수정

src/main/resources/templates/common/adminHeader.html, src/main/resources/templates/customerService/faq.html
adminHeader 불필요 사이드메뉴 수정 및 faq 3번질문 수정
=> adminHeader 불필요 사이드메뉴 수정 및 faq 3번질문 수정

src/main/resources/static/css/admin/admin.css, src/main/resources/static/css/admin/adminDashBoard.css, src/main/resources/static/css/admin/contents.css, src/main/resources/static/css/admin/member.css, src/main/resources/static/css/admin/memberActive.css, src/main/resources/static/css/admin/query.css, src/main/resources/static/css/admin/trainer.css, src/main/resources/static/css/admin/trainerActive.css, src/main/resources/static/css/board/board.css, src/main/resources/static/css/board/boardDetail.css, src/main/resources/static/css/board/boardWrite.css, src/main/resources/static/css/board/classList.css, src/main/resources/static/css/board/comment.css, src/main/resources/static/css/classList/memberClassList.css, src/main/resources/static/css/classList/trainerClassList.css, src/main/resources/static/css/customerService/faq.css, src/main/resources/static/css/login/afterFindPw.css, src/main/resources/static/css/login/findPw.css, src/main/resources/static/css/login/login.css, src/main/resources/static/css/member/memberCheckPw.css, src/main/resources/static/css/member/statusChange.css, src/main/resources/static/css/myPage/memberMyActivities.css, src/main/resources/static/css/myPage/memberMyPage-style.css, src/main/resources/static/css/myPage/trainerMyPage-style.css, src/main/resources/templates/classList/classList.html, src/main/resources/templates/login/afterFindPw.html, src/main/resources/templates/login/findPw.html, src/main/resources/templates/member/statusChange.html, src/main/resources/templates/trainer/findpw.html, src/main/resources/templates/trainer/trainerCheckPw.html
=> css 폰트 및 라인 수정 HTML도 몇개 건들긴 했어염
